Creates AWS infrastructure

diff --git a/create-aws-infrastructure b/create-aws-infrastructure
--- a/create-aws-infrastructure
+++ b/create-aws-infrastructure
@@ -1,7 +1,9 @@
 #!/bin/bash -x
 
+(return 0 2>/dev/null) && sourced=1 || { echo "Error: Script must be sourced"; exit 1; }
+
 echo "Virtual Private Cloud Network"
-export VPC_ID=$(aws ec2 create-vpc \
+VPC_ID=$(aws ec2 create-vpc \
   --cidr-block 10.240.0.0/16 \
   --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=kubernetes-the-hard-way}]' \
   --output text --query 'Vpc.VpcId')
@@ -14,21 +16,15 @@ aws ec2 modify-vpc-attribute \
   --vpc-id "${VPC_ID}" \
   --enable-dns-hostnames '{"Value": true}'
 
-echo "Press enter to continue..."
-read -r name
-
 echo "Create Subnet"
-export SUBNET_ID=$(aws ec2 create-subnet \
+SUBNET_ID=$(aws ec2 create-subnet \
   --vpc-id "${VPC_ID}" \
   --cidr-block 10.240.0.0/24 \
   --tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=kubernetes-the-hard-way},{Key=kubernetes.io/role/internal-elb,Value=1},{Key=kubernetes.io/cluster/kubernetes-the-hard-way,Value=owned}]' \
   --output text --query 'Subnet.SubnetId')
 
-echo "Press enter to continue..."
-read -r name
-
 echo "Create Internet Gateway"
-export INTERNET_GATEWAY_ID=$(aws ec2 create-internet-gateway \
+INTERNET_GATEWAY_ID=$(aws ec2 create-internet-gateway \
   --tag-specifications 'ResourceType=internet-gateway,Tags=[{Key=Name,Value=kubernetes-the-hard-way}]' \
   --output text --query 'InternetGateway.InternetGatewayId')
 
@@ -36,11 +32,8 @@ aws ec2 attach-internet-gateway \
   --internet-gateway-id "${INTERNET_GATEWAY_ID}" \
   --vpc-id "${VPC_ID}"
 
-echo "Press enter to continue..."
-read -r name
-
 echo "Create Route Table"
-export ROUTE_TABLE_ID=$(aws ec2 create-route-table \
+ROUTE_TABLE_ID=$(aws ec2 create-route-table \
   --vpc-id "${VPC_ID}" \
   --tag-specifications 'ResourceType=route-table,Tags=[{Key=Name,Value=kubernetes-the-hard-way}]' \
   --output text --query 'RouteTable.RouteTableId')
@@ -54,11 +47,8 @@ aws ec2 create-route \
   --destination-cidr-block 0.0.0.0/0 \
   --gateway-id "${INTERNET_GATEWAY_ID}"
 
-echo "Press enter to continue..."
-read -r name
-
 echo "Firewall Rules"
-export SECURITY_GROUP_ID=$(aws ec2 create-security-group \
+SECURITY_GROUP_ID=$(aws ec2 create-security-group \
   --group-name kubernetes-the-hard-way \
   --description "Kubernetes The Hard Way security group" \
   --vpc-id "${VPC_ID}" \
@@ -93,22 +83,15 @@ aws ec2 describe-security-group-rules \
   --query 'sort_by(SecurityGroupRules, &CidrIpv4)[].{a_Protocol:IpProtocol,b_FromPort:FromPort,c_ToPort:ToPort,d_Cidr:CidrIpv4}' \
   --output table
 
-echo "Press enter to continue..."
-read -r name
-
 echo "Kubernetes Public IP Address"
-export ALLOCATION_ID=$(aws ec2 allocate-address \
+ALLOCATION_ID=$(aws ec2 allocate-address \
   --domain vpc \
   --tag-specifications 'ResourceType=elastic-ip,Tags=[{Key=Name,Value=kubernetes-the-hard-way}]' \
   --output text --query 'AllocationId')
 
 aws ec2 describe-addresses --allocation-ids "${ALLOCATION_ID}"
 
-echo "Press enter to continue..."
-read -r name
-
-echo "Compute Instances"
-echo "Create SSH key pair"
+echo "Compute Instances - Create SSH key pair"
 aws ec2 create-key-pair \
   --key-name kubernetes-the-hard-way \
   --output text --query 'KeyMaterial' \
@@ -116,7 +99,7 @@ aws ec2 create-key-pair \
 
 chmod 600 kubernetes-the-hard-way.id_rsa
 
-echo "Find instance image ID"
+echo "Compute Instances - Find instance image ID"
 IMAGE_ID=$(aws ec2 describe-images --owners 099720109477 \
   --filters \
   'Name=root-device-type,Values=ebs' \
@@ -126,7 +109,7 @@ IMAGE_ID=$(aws ec2 describe-images --owners 099720109477 \
 
 echo "${IMAGE_ID}"
 
-echo "Create Kubernetes Controllers"
+echo "Compute Instances - Create Kubernetes Controllers"
 for i in 0 1 2; do
   instance_id=$(aws ec2 run-instances \
     --associate-public-ip-address \
@@ -146,10 +129,7 @@ for i in 0 1 2; do
     --no-source-dest-check
 done
 
-echo "Press enter to continue..."
-read -r name
-
-echo "Create Kubernetes Workers"
+echo "Compute Instances - Create Kubernetes Workers"
 for i in 0 1 2; do
   instance_id=$(aws ec2 run-instances \
     --associate-public-ip-address \
@@ -174,5 +154,4 @@ aws ec2 describe-instances \
   --query 'sort_by(Reservations[].Instances[],&PrivateIpAddress)[].{d_INTERNAL_IP:PrivateIpAddress,e_EXTERNAL_IP:PublicIpAddress,a_NAME:Tags[?Key==`Name`].Value | [0],b_ZONE:Placement.AvailabilityZone,c_MACHINE_TYPE:InstanceType,f_STATUS:State.Name}' \
   --output table
 
-echo "This part is done - Press enter to continue..."
-read -r name
+echo "This part is done!"
